\connect studs

\i /docker-entrypoint-initdb.d/drop.sql

create table inode
(
    no   bigint generated by default as identity
        primary key,
    type varchar(64) not null,
    text text
);

create table dentry
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(255)                                                not null,
    inode_no bigint references inode on update cascade on delete cascade not null
);

create table token
(
    id      bigint generated by default as identity
        primary key,
    token   varchar(255) unique                                         not null,
    root_no bigint references inode on update cascade on delete cascade not null
);

create table children
(
    parent_no bigint references inode on update cascade on delete cascade  not null,
    child_no  bigint references dentry on update cascade on delete cascade not null,
    constraint children_pk unique (parent_no, child_no)
);