// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

public interface ChildrenMsgDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.ChildrenMsgDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return The status.
   */
  snfs.fserver.protocol.ErrStatus getStatus();

  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  java.util.List<snfs.fserver.protocol.DentryDto> 
      getChildrenList();
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  snfs.fserver.protocol.DentryDto getChildren(int index);
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  java.util.List<? extends snfs.fserver.protocol.DentryDtoOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  snfs.fserver.protocol.DentryDtoOrBuilder getChildrenOrBuilder(
      int index);
}
