// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

/**
 * Protobuf type {@code protocol.ChildrenMsgDto}
 */
public final class ChildrenMsgDto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol.ChildrenMsgDto)
    ChildrenMsgDtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ChildrenMsgDto.class.getName());
  }
  // Use ChildrenMsgDto.newBuilder() to construct.
  private ChildrenMsgDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChildrenMsgDto() {
    status_ = 1;
    children_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_ChildrenMsgDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_ChildrenMsgDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            snfs.fserver.protocol.ChildrenMsgDto.class, snfs.fserver.protocol.ChildrenMsgDto.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 1;
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public snfs.fserver.protocol.ErrStatus getStatus() {
    snfs.fserver.protocol.ErrStatus result = snfs.fserver.protocol.ErrStatus.forNumber(status_);
    return result == null ? snfs.fserver.protocol.ErrStatus.OK : result;
  }

  public static final int CHILDREN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<snfs.fserver.protocol.DentryDto> children_;
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  @java.lang.Override
  public java.util.List<snfs.fserver.protocol.DentryDto> getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends snfs.fserver.protocol.DentryDtoOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  @java.lang.Override
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  @java.lang.Override
  public snfs.fserver.protocol.DentryDto getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <code>repeated .protocol.DentryDto children = 2;</code>
   */
  @java.lang.Override
  public snfs.fserver.protocol.DentryDtoOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getChildrenCount(); i++) {
      if (!getChildren(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, status_);
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(2, children_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, children_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof snfs.fserver.protocol.ChildrenMsgDto)) {
      return super.equals(obj);
    }
    snfs.fserver.protocol.ChildrenMsgDto other = (snfs.fserver.protocol.ChildrenMsgDto) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (status_ != other.status_) return false;
    }
    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
    }
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static snfs.fserver.protocol.ChildrenMsgDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static snfs.fserver.protocol.ChildrenMsgDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.ChildrenMsgDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(snfs.fserver.protocol.ChildrenMsgDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.ChildrenMsgDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.ChildrenMsgDto)
      snfs.fserver.protocol.ChildrenMsgDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_ChildrenMsgDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_ChildrenMsgDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snfs.fserver.protocol.ChildrenMsgDto.class, snfs.fserver.protocol.ChildrenMsgDto.Builder.class);
    }

    // Construct using snfs.fserver.protocol.ChildrenMsgDto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 1;
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
      } else {
        children_ = null;
        childrenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_ChildrenMsgDto_descriptor;
    }

    @java.lang.Override
    public snfs.fserver.protocol.ChildrenMsgDto getDefaultInstanceForType() {
      return snfs.fserver.protocol.ChildrenMsgDto.getDefaultInstance();
    }

    @java.lang.Override
    public snfs.fserver.protocol.ChildrenMsgDto build() {
      snfs.fserver.protocol.ChildrenMsgDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public snfs.fserver.protocol.ChildrenMsgDto buildPartial() {
      snfs.fserver.protocol.ChildrenMsgDto result = new snfs.fserver.protocol.ChildrenMsgDto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(snfs.fserver.protocol.ChildrenMsgDto result) {
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
    }

    private void buildPartial0(snfs.fserver.protocol.ChildrenMsgDto result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof snfs.fserver.protocol.ChildrenMsgDto) {
        return mergeFrom((snfs.fserver.protocol.ChildrenMsgDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(snfs.fserver.protocol.ChildrenMsgDto other) {
      if (other == snfs.fserver.protocol.ChildrenMsgDto.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000002);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasStatus()) {
        return false;
      }
      for (int i = 0; i < getChildrenCount(); i++) {
        if (!getChildren(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              snfs.fserver.protocol.ErrStatus tmpValue =
                  snfs.fserver.protocol.ErrStatus.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                status_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            case 18: {
              snfs.fserver.protocol.DentryDto m =
                  input.readMessage(
                      snfs.fserver.protocol.DentryDto.parser(),
                      extensionRegistry);
              if (childrenBuilder_ == null) {
                ensureChildrenIsMutable();
                children_.add(m);
              } else {
                childrenBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 1;
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public snfs.fserver.protocol.ErrStatus getStatus() {
      snfs.fserver.protocol.ErrStatus result = snfs.fserver.protocol.ErrStatus.forNumber(status_);
      return result == null ? snfs.fserver.protocol.ErrStatus.OK : result;
    }
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(snfs.fserver.protocol.ErrStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 1;
      onChanged();
      return this;
    }

    private java.util.List<snfs.fserver.protocol.DentryDto> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        children_ = new java.util.ArrayList<snfs.fserver.protocol.DentryDto>(children_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        snfs.fserver.protocol.DentryDto, snfs.fserver.protocol.DentryDto.Builder, snfs.fserver.protocol.DentryDtoOrBuilder> childrenBuilder_;

    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public java.util.List<snfs.fserver.protocol.DentryDto> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public snfs.fserver.protocol.DentryDto getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder setChildren(
        int index, snfs.fserver.protocol.DentryDto value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder setChildren(
        int index, snfs.fserver.protocol.DentryDto.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder addChildren(snfs.fserver.protocol.DentryDto value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder addChildren(
        int index, snfs.fserver.protocol.DentryDto value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder addChildren(
        snfs.fserver.protocol.DentryDto.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder addChildren(
        int index, snfs.fserver.protocol.DentryDto.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends snfs.fserver.protocol.DentryDto> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public snfs.fserver.protocol.DentryDto.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public snfs.fserver.protocol.DentryDtoOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public java.util.List<? extends snfs.fserver.protocol.DentryDtoOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public snfs.fserver.protocol.DentryDto.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          snfs.fserver.protocol.DentryDto.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public snfs.fserver.protocol.DentryDto.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, snfs.fserver.protocol.DentryDto.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.DentryDto children = 2;</code>
     */
    public java.util.List<snfs.fserver.protocol.DentryDto.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        snfs.fserver.protocol.DentryDto, snfs.fserver.protocol.DentryDto.Builder, snfs.fserver.protocol.DentryDtoOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            snfs.fserver.protocol.DentryDto, snfs.fserver.protocol.DentryDto.Builder, snfs.fserver.protocol.DentryDtoOrBuilder>(
                children_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:protocol.ChildrenMsgDto)
  }

  // @@protoc_insertion_point(class_scope:protocol.ChildrenMsgDto)
  private static final snfs.fserver.protocol.ChildrenMsgDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new snfs.fserver.protocol.ChildrenMsgDto();
  }

  public static snfs.fserver.protocol.ChildrenMsgDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChildrenMsgDto>
      PARSER = new com.google.protobuf.AbstractParser<ChildrenMsgDto>() {
    @java.lang.Override
    public ChildrenMsgDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChildrenMsgDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChildrenMsgDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public snfs.fserver.protocol.ChildrenMsgDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

