// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

public interface DentryDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.DentryDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required .protocol.InodeDto inode = 2;</code>
   * @return Whether the inode field is set.
   */
  boolean hasInode();
  /**
   * <code>required .protocol.InodeDto inode = 2;</code>
   * @return The inode.
   */
  snfs.fserver.protocol.InodeDto getInode();
  /**
   * <code>required .protocol.InodeDto inode = 2;</code>
   */
  snfs.fserver.protocol.InodeDtoOrBuilder getInodeOrBuilder();
}
