// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

/**
 * Protobuf type {@code protocol.DentryDto}
 */
public final class DentryDto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol.DentryDto)
    DentryDtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      DentryDto.class.getName());
  }
  // Use DentryDto.newBuilder() to construct.
  private DentryDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DentryDto() {
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_DentryDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_DentryDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            snfs.fserver.protocol.DentryDto.class, snfs.fserver.protocol.DentryDto.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INODE_FIELD_NUMBER = 2;
  private snfs.fserver.protocol.InodeDto inode_;
  /**
   * <code>required .protocol.InodeDto inode = 2;</code>
   * @return Whether the inode field is set.
   */
  @java.lang.Override
  public boolean hasInode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required .protocol.InodeDto inode = 2;</code>
   * @return The inode.
   */
  @java.lang.Override
  public snfs.fserver.protocol.InodeDto getInode() {
    return inode_ == null ? snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
  }
  /**
   * <code>required .protocol.InodeDto inode = 2;</code>
   */
  @java.lang.Override
  public snfs.fserver.protocol.InodeDtoOrBuilder getInodeOrBuilder() {
    return inode_ == null ? snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasInode()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getInode().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getInode());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInode());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof snfs.fserver.protocol.DentryDto)) {
      return super.equals(obj);
    }
    snfs.fserver.protocol.DentryDto other = (snfs.fserver.protocol.DentryDto) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasInode() != other.hasInode()) return false;
    if (hasInode()) {
      if (!getInode()
          .equals(other.getInode())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasInode()) {
      hash = (37 * hash) + INODE_FIELD_NUMBER;
      hash = (53 * hash) + getInode().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static snfs.fserver.protocol.DentryDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static snfs.fserver.protocol.DentryDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static snfs.fserver.protocol.DentryDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.DentryDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(snfs.fserver.protocol.DentryDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.DentryDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.DentryDto)
      snfs.fserver.protocol.DentryDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_DentryDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_DentryDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snfs.fserver.protocol.DentryDto.class, snfs.fserver.protocol.DentryDto.Builder.class);
    }

    // Construct using snfs.fserver.protocol.DentryDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getInodeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      inode_ = null;
      if (inodeBuilder_ != null) {
        inodeBuilder_.dispose();
        inodeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_DentryDto_descriptor;
    }

    @java.lang.Override
    public snfs.fserver.protocol.DentryDto getDefaultInstanceForType() {
      return snfs.fserver.protocol.DentryDto.getDefaultInstance();
    }

    @java.lang.Override
    public snfs.fserver.protocol.DentryDto build() {
      snfs.fserver.protocol.DentryDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public snfs.fserver.protocol.DentryDto buildPartial() {
      snfs.fserver.protocol.DentryDto result = new snfs.fserver.protocol.DentryDto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(snfs.fserver.protocol.DentryDto result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.inode_ = inodeBuilder_ == null
            ? inode_
            : inodeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof snfs.fserver.protocol.DentryDto) {
        return mergeFrom((snfs.fserver.protocol.DentryDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(snfs.fserver.protocol.DentryDto other) {
      if (other == snfs.fserver.protocol.DentryDto.getDefaultInstance()) return this;
      if (other.hasName()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasInode()) {
        mergeInode(other.getInode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasName()) {
        return false;
      }
      if (!hasInode()) {
        return false;
      }
      if (!getInode().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private snfs.fserver.protocol.InodeDto inode_;
    private com.google.protobuf.SingleFieldBuilder<
        snfs.fserver.protocol.InodeDto, snfs.fserver.protocol.InodeDto.Builder, snfs.fserver.protocol.InodeDtoOrBuilder> inodeBuilder_;
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     * @return Whether the inode field is set.
     */
    public boolean hasInode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     * @return The inode.
     */
    public snfs.fserver.protocol.InodeDto getInode() {
      if (inodeBuilder_ == null) {
        return inode_ == null ? snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
      } else {
        return inodeBuilder_.getMessage();
      }
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    public Builder setInode(snfs.fserver.protocol.InodeDto value) {
      if (inodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inode_ = value;
      } else {
        inodeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    public Builder setInode(
        snfs.fserver.protocol.InodeDto.Builder builderForValue) {
      if (inodeBuilder_ == null) {
        inode_ = builderForValue.build();
      } else {
        inodeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    public Builder mergeInode(snfs.fserver.protocol.InodeDto value) {
      if (inodeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          inode_ != null &&
          inode_ != snfs.fserver.protocol.InodeDto.getDefaultInstance()) {
          getInodeBuilder().mergeFrom(value);
        } else {
          inode_ = value;
        }
      } else {
        inodeBuilder_.mergeFrom(value);
      }
      if (inode_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    public Builder clearInode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      inode_ = null;
      if (inodeBuilder_ != null) {
        inodeBuilder_.dispose();
        inodeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    public snfs.fserver.protocol.InodeDto.Builder getInodeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInodeFieldBuilder().getBuilder();
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    public snfs.fserver.protocol.InodeDtoOrBuilder getInodeOrBuilder() {
      if (inodeBuilder_ != null) {
        return inodeBuilder_.getMessageOrBuilder();
      } else {
        return inode_ == null ?
            snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
      }
    }
    /**
     * <code>required .protocol.InodeDto inode = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        snfs.fserver.protocol.InodeDto, snfs.fserver.protocol.InodeDto.Builder, snfs.fserver.protocol.InodeDtoOrBuilder> 
        getInodeFieldBuilder() {
      if (inodeBuilder_ == null) {
        inodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            snfs.fserver.protocol.InodeDto, snfs.fserver.protocol.InodeDto.Builder, snfs.fserver.protocol.InodeDtoOrBuilder>(
                getInode(),
                getParentForChildren(),
                isClean());
        inode_ = null;
      }
      return inodeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:protocol.DentryDto)
  }

  // @@protoc_insertion_point(class_scope:protocol.DentryDto)
  private static final snfs.fserver.protocol.DentryDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new snfs.fserver.protocol.DentryDto();
  }

  public static snfs.fserver.protocol.DentryDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DentryDto>
      PARSER = new com.google.protobuf.AbstractParser<DentryDto>() {
    @java.lang.Override
    public DentryDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DentryDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DentryDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public snfs.fserver.protocol.DentryDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

