// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

public final class FsProto {
  private FsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      FsProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_MsgDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_MsgDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_InodeMsgDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_InodeMsgDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChildrenMsgDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ChildrenMsgDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_TextMsgDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_TextMsgDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_DentryDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_DentryDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_InodeDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_InodeDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_InodeChildren_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_InodeChildren_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010fs.proto\022\010protocol\"-\n\006MsgDto\022#\n\006status" +
      "\030\001 \002(\0162\023.protocol.ErrStatus\"U\n\013InodeMsgD" +
      "to\022#\n\006status\030\001 \002(\0162\023.protocol.ErrStatus\022" +
      "!\n\005inode\030\002 \001(\0132\022.protocol.InodeDto\"\\\n\016Ch" +
      "ildrenMsgDto\022#\n\006status\030\001 \002(\0162\023.protocol." +
      "ErrStatus\022%\n\010children\030\002 \003(\0132\023.protocol.D" +
      "entryDto\"?\n\nTextMsgDto\022#\n\006status\030\001 \002(\0162\023" +
      ".protocol.ErrStatus\022\014\n\004text\030\002 \001(\t\"<\n\tDen" +
      "tryDto\022\014\n\004name\030\001 \002(\t\022!\n\005inode\030\002 \002(\0132\022.pr" +
      "otocol.InodeDto\"G\n\010InodeDto\022\n\n\002no\030\001 \002(\005\022" +
      "!\n\004type\030\002 \002(\0162\023.protocol.InodeType\022\014\n\004si" +
      "ze\030\004 \002(\005\"6\n\rInodeChildren\022%\n\010children\030\001 " +
      "\003(\0132\023.protocol.DentryDto*\035\n\tInodeType\022\007\n" +
      "\003REG\020\001\022\007\n\003DIR\020\002*^\n\tErrStatus\022\006\n\002OK\020\001\022\013\n\007" +
      "MISSING\020\002\022\n\n\006NOTDIR\020\003\022\t\n\005ISDIR\020\004\022\t\n\005EMPT" +
      "Y\020\005\022\013\n\007UNKNOWN\020\006\022\r\n\tDUPLICATE\020\007B\"\n\025snfs." +
      "fserver.protocolB\007FsProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_MsgDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_MsgDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_MsgDto_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_protocol_InodeMsgDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_InodeMsgDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_InodeMsgDto_descriptor,
        new java.lang.String[] { "Status", "Inode", });
    internal_static_protocol_ChildrenMsgDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_ChildrenMsgDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_ChildrenMsgDto_descriptor,
        new java.lang.String[] { "Status", "Children", });
    internal_static_protocol_TextMsgDto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_TextMsgDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_TextMsgDto_descriptor,
        new java.lang.String[] { "Status", "Text", });
    internal_static_protocol_DentryDto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_DentryDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_DentryDto_descriptor,
        new java.lang.String[] { "Name", "Inode", });
    internal_static_protocol_InodeDto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protocol_InodeDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_InodeDto_descriptor,
        new java.lang.String[] { "No", "Type", "Size", });
    internal_static_protocol_InodeChildren_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protocol_InodeChildren_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protocol_InodeChildren_descriptor,
        new java.lang.String[] { "Children", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
