// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

public interface InodeDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.InodeDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 no = 1;</code>
   * @return Whether the no field is set.
   */
  boolean hasNo();
  /**
   * <code>required int32 no = 1;</code>
   * @return The no.
   */
  int getNo();

  /**
   * <code>required .protocol.InodeType type = 2;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required .protocol.InodeType type = 2;</code>
   * @return The type.
   */
  snfs.fserver.protocol.InodeType getType();

  /**
   * <code>required int32 size = 4;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>required int32 size = 4;</code>
   * @return The size.
   */
  int getSize();
}
