// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

/**
 * Protobuf type {@code protocol.InodeChildren}
 */
public final class InodeChildren extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol.InodeChildren)
    InodeChildrenOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      InodeChildren.class.getName());
  }
  // Use InodeChildren.newBuilder() to construct.
  private InodeChildren(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InodeChildren() {
    children_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeChildren_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeChildren_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            snfs.fserver.protocol.InodeChildren.class, snfs.fserver.protocol.InodeChildren.Builder.class);
  }

  public static final int CHILDREN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<snfs.fserver.protocol.DentryDto> children_;
  /**
   * <code>repeated .protocol.DentryDto children = 1;</code>
   */
  @java.lang.Override
  public java.util.List<snfs.fserver.protocol.DentryDto> getChildrenList() {
    return children_;
  }
  /**
   * <code>repeated .protocol.DentryDto children = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends snfs.fserver.protocol.DentryDtoOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <code>repeated .protocol.DentryDto children = 1;</code>
   */
  @java.lang.Override
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <code>repeated .protocol.DentryDto children = 1;</code>
   */
  @java.lang.Override
  public snfs.fserver.protocol.DentryDto getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <code>repeated .protocol.DentryDto children = 1;</code>
   */
  @java.lang.Override
  public snfs.fserver.protocol.DentryDtoOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getChildrenCount(); i++) {
      if (!getChildren(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(1, children_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, children_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof snfs.fserver.protocol.InodeChildren)) {
      return super.equals(obj);
    }
    snfs.fserver.protocol.InodeChildren other = (snfs.fserver.protocol.InodeChildren) obj;

    if (!getChildrenList()
        .equals(other.getChildrenList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static snfs.fserver.protocol.InodeChildren parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static snfs.fserver.protocol.InodeChildren parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static snfs.fserver.protocol.InodeChildren parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.InodeChildren parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(snfs.fserver.protocol.InodeChildren prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.InodeChildren}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.InodeChildren)
      snfs.fserver.protocol.InodeChildrenOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeChildren_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeChildren_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snfs.fserver.protocol.InodeChildren.class, snfs.fserver.protocol.InodeChildren.Builder.class);
    }

    // Construct using snfs.fserver.protocol.InodeChildren.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
      } else {
        children_ = null;
        childrenBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeChildren_descriptor;
    }

    @java.lang.Override
    public snfs.fserver.protocol.InodeChildren getDefaultInstanceForType() {
      return snfs.fserver.protocol.InodeChildren.getDefaultInstance();
    }

    @java.lang.Override
    public snfs.fserver.protocol.InodeChildren build() {
      snfs.fserver.protocol.InodeChildren result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public snfs.fserver.protocol.InodeChildren buildPartial() {
      snfs.fserver.protocol.InodeChildren result = new snfs.fserver.protocol.InodeChildren(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(snfs.fserver.protocol.InodeChildren result) {
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
    }

    private void buildPartial0(snfs.fserver.protocol.InodeChildren result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof snfs.fserver.protocol.InodeChildren) {
        return mergeFrom((snfs.fserver.protocol.InodeChildren)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(snfs.fserver.protocol.InodeChildren other) {
      if (other == snfs.fserver.protocol.InodeChildren.getDefaultInstance()) return this;
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000001);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getChildrenCount(); i++) {
        if (!getChildren(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              snfs.fserver.protocol.DentryDto m =
                  input.readMessage(
                      snfs.fserver.protocol.DentryDto.parser(),
                      extensionRegistry);
              if (childrenBuilder_ == null) {
                ensureChildrenIsMutable();
                children_.add(m);
              } else {
                childrenBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<snfs.fserver.protocol.DentryDto> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        children_ = new java.util.ArrayList<snfs.fserver.protocol.DentryDto>(children_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        snfs.fserver.protocol.DentryDto, snfs.fserver.protocol.DentryDto.Builder, snfs.fserver.protocol.DentryDtoOrBuilder> childrenBuilder_;

    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public java.util.List<snfs.fserver.protocol.DentryDto> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public snfs.fserver.protocol.DentryDto getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder setChildren(
        int index, snfs.fserver.protocol.DentryDto value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder setChildren(
        int index, snfs.fserver.protocol.DentryDto.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder addChildren(snfs.fserver.protocol.DentryDto value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder addChildren(
        int index, snfs.fserver.protocol.DentryDto value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder addChildren(
        snfs.fserver.protocol.DentryDto.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder addChildren(
        int index, snfs.fserver.protocol.DentryDto.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends snfs.fserver.protocol.DentryDto> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public snfs.fserver.protocol.DentryDto.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public snfs.fserver.protocol.DentryDtoOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public java.util.List<? extends snfs.fserver.protocol.DentryDtoOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public snfs.fserver.protocol.DentryDto.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          snfs.fserver.protocol.DentryDto.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public snfs.fserver.protocol.DentryDto.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, snfs.fserver.protocol.DentryDto.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.DentryDto children = 1;</code>
     */
    public java.util.List<snfs.fserver.protocol.DentryDto.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        snfs.fserver.protocol.DentryDto, snfs.fserver.protocol.DentryDto.Builder, snfs.fserver.protocol.DentryDtoOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            snfs.fserver.protocol.DentryDto, snfs.fserver.protocol.DentryDto.Builder, snfs.fserver.protocol.DentryDtoOrBuilder>(
                children_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:protocol.InodeChildren)
  }

  // @@protoc_insertion_point(class_scope:protocol.InodeChildren)
  private static final snfs.fserver.protocol.InodeChildren DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new snfs.fserver.protocol.InodeChildren();
  }

  public static snfs.fserver.protocol.InodeChildren getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InodeChildren>
      PARSER = new com.google.protobuf.AbstractParser<InodeChildren>() {
    @java.lang.Override
    public InodeChildren parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InodeChildren> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InodeChildren> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public snfs.fserver.protocol.InodeChildren getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

