// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

/**
 * Protobuf enum {@code protocol.InodeType}
 */
public enum InodeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>REG = 1;</code>
   */
  REG(1),
  /**
   * <code>DIR = 2;</code>
   */
  DIR(2),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      InodeType.class.getName());
  }
  /**
   * <code>REG = 1;</code>
   */
  public static final int REG_VALUE = 1;
  /**
   * <code>DIR = 2;</code>
   */
  public static final int DIR_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InodeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static InodeType forNumber(int value) {
    switch (value) {
      case 1: return REG;
      case 2: return DIR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InodeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InodeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InodeType>() {
          public InodeType findValueByNumber(int number) {
            return InodeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return snfs.fserver.protocol.FsProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final InodeType[] VALUES = values();

  public static InodeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private InodeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protocol.InodeType)
}

