// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

/**
 * Protobuf type {@code protocol.InodeMsgDto}
 */
public final class InodeMsgDto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:protocol.InodeMsgDto)
    InodeMsgDtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      InodeMsgDto.class.getName());
  }
  // Use InodeMsgDto.newBuilder() to construct.
  private InodeMsgDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InodeMsgDto() {
    status_ = 1;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeMsgDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeMsgDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            snfs.fserver.protocol.InodeMsgDto.class, snfs.fserver.protocol.InodeMsgDto.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 1;
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public snfs.fserver.protocol.ErrStatus getStatus() {
    snfs.fserver.protocol.ErrStatus result = snfs.fserver.protocol.ErrStatus.forNumber(status_);
    return result == null ? snfs.fserver.protocol.ErrStatus.OK : result;
  }

  public static final int INODE_FIELD_NUMBER = 2;
  private snfs.fserver.protocol.InodeDto inode_;
  /**
   * <code>optional .protocol.InodeDto inode = 2;</code>
   * @return Whether the inode field is set.
   */
  @java.lang.Override
  public boolean hasInode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .protocol.InodeDto inode = 2;</code>
   * @return The inode.
   */
  @java.lang.Override
  public snfs.fserver.protocol.InodeDto getInode() {
    return inode_ == null ? snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
  }
  /**
   * <code>optional .protocol.InodeDto inode = 2;</code>
   */
  @java.lang.Override
  public snfs.fserver.protocol.InodeDtoOrBuilder getInodeOrBuilder() {
    return inode_ == null ? snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasInode()) {
      if (!getInode().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, status_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getInode());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInode());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof snfs.fserver.protocol.InodeMsgDto)) {
      return super.equals(obj);
    }
    snfs.fserver.protocol.InodeMsgDto other = (snfs.fserver.protocol.InodeMsgDto) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (status_ != other.status_) return false;
    }
    if (hasInode() != other.hasInode()) return false;
    if (hasInode()) {
      if (!getInode()
          .equals(other.getInode())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
    }
    if (hasInode()) {
      hash = (37 * hash) + INODE_FIELD_NUMBER;
      hash = (53 * hash) + getInode().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static snfs.fserver.protocol.InodeMsgDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static snfs.fserver.protocol.InodeMsgDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static snfs.fserver.protocol.InodeMsgDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(snfs.fserver.protocol.InodeMsgDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.InodeMsgDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.InodeMsgDto)
      snfs.fserver.protocol.InodeMsgDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeMsgDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeMsgDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              snfs.fserver.protocol.InodeMsgDto.class, snfs.fserver.protocol.InodeMsgDto.Builder.class);
    }

    // Construct using snfs.fserver.protocol.InodeMsgDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getInodeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 1;
      inode_ = null;
      if (inodeBuilder_ != null) {
        inodeBuilder_.dispose();
        inodeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return snfs.fserver.protocol.FsProto.internal_static_protocol_InodeMsgDto_descriptor;
    }

    @java.lang.Override
    public snfs.fserver.protocol.InodeMsgDto getDefaultInstanceForType() {
      return snfs.fserver.protocol.InodeMsgDto.getDefaultInstance();
    }

    @java.lang.Override
    public snfs.fserver.protocol.InodeMsgDto build() {
      snfs.fserver.protocol.InodeMsgDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public snfs.fserver.protocol.InodeMsgDto buildPartial() {
      snfs.fserver.protocol.InodeMsgDto result = new snfs.fserver.protocol.InodeMsgDto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(snfs.fserver.protocol.InodeMsgDto result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.inode_ = inodeBuilder_ == null
            ? inode_
            : inodeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof snfs.fserver.protocol.InodeMsgDto) {
        return mergeFrom((snfs.fserver.protocol.InodeMsgDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(snfs.fserver.protocol.InodeMsgDto other) {
      if (other == snfs.fserver.protocol.InodeMsgDto.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      if (other.hasInode()) {
        mergeInode(other.getInode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasStatus()) {
        return false;
      }
      if (hasInode()) {
        if (!getInode().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              snfs.fserver.protocol.ErrStatus tmpValue =
                  snfs.fserver.protocol.ErrStatus.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                status_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getInodeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int status_ = 1;
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public snfs.fserver.protocol.ErrStatus getStatus() {
      snfs.fserver.protocol.ErrStatus result = snfs.fserver.protocol.ErrStatus.forNumber(status_);
      return result == null ? snfs.fserver.protocol.ErrStatus.OK : result;
    }
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(snfs.fserver.protocol.ErrStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .protocol.ErrStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 1;
      onChanged();
      return this;
    }

    private snfs.fserver.protocol.InodeDto inode_;
    private com.google.protobuf.SingleFieldBuilder<
        snfs.fserver.protocol.InodeDto, snfs.fserver.protocol.InodeDto.Builder, snfs.fserver.protocol.InodeDtoOrBuilder> inodeBuilder_;
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     * @return Whether the inode field is set.
     */
    public boolean hasInode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     * @return The inode.
     */
    public snfs.fserver.protocol.InodeDto getInode() {
      if (inodeBuilder_ == null) {
        return inode_ == null ? snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
      } else {
        return inodeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    public Builder setInode(snfs.fserver.protocol.InodeDto value) {
      if (inodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inode_ = value;
      } else {
        inodeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    public Builder setInode(
        snfs.fserver.protocol.InodeDto.Builder builderForValue) {
      if (inodeBuilder_ == null) {
        inode_ = builderForValue.build();
      } else {
        inodeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    public Builder mergeInode(snfs.fserver.protocol.InodeDto value) {
      if (inodeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          inode_ != null &&
          inode_ != snfs.fserver.protocol.InodeDto.getDefaultInstance()) {
          getInodeBuilder().mergeFrom(value);
        } else {
          inode_ = value;
        }
      } else {
        inodeBuilder_.mergeFrom(value);
      }
      if (inode_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    public Builder clearInode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      inode_ = null;
      if (inodeBuilder_ != null) {
        inodeBuilder_.dispose();
        inodeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    public snfs.fserver.protocol.InodeDto.Builder getInodeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInodeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    public snfs.fserver.protocol.InodeDtoOrBuilder getInodeOrBuilder() {
      if (inodeBuilder_ != null) {
        return inodeBuilder_.getMessageOrBuilder();
      } else {
        return inode_ == null ?
            snfs.fserver.protocol.InodeDto.getDefaultInstance() : inode_;
      }
    }
    /**
     * <code>optional .protocol.InodeDto inode = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        snfs.fserver.protocol.InodeDto, snfs.fserver.protocol.InodeDto.Builder, snfs.fserver.protocol.InodeDtoOrBuilder> 
        getInodeFieldBuilder() {
      if (inodeBuilder_ == null) {
        inodeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            snfs.fserver.protocol.InodeDto, snfs.fserver.protocol.InodeDto.Builder, snfs.fserver.protocol.InodeDtoOrBuilder>(
                getInode(),
                getParentForChildren(),
                isClean());
        inode_ = null;
      }
      return inodeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:protocol.InodeMsgDto)
  }

  // @@protoc_insertion_point(class_scope:protocol.InodeMsgDto)
  private static final snfs.fserver.protocol.InodeMsgDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new snfs.fserver.protocol.InodeMsgDto();
  }

  public static snfs.fserver.protocol.InodeMsgDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InodeMsgDto>
      PARSER = new com.google.protobuf.AbstractParser<InodeMsgDto>() {
    @java.lang.Override
    public InodeMsgDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InodeMsgDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InodeMsgDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public snfs.fserver.protocol.InodeMsgDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

