// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

public interface InodeMsgDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.InodeMsgDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return The status.
   */
  snfs.fserver.protocol.ErrStatus getStatus();

  /**
   * <code>optional .protocol.InodeDto inode = 2;</code>
   * @return Whether the inode field is set.
   */
  boolean hasInode();
  /**
   * <code>optional .protocol.InodeDto inode = 2;</code>
   * @return The inode.
   */
  snfs.fserver.protocol.InodeDto getInode();
  /**
   * <code>optional .protocol.InodeDto inode = 2;</code>
   */
  snfs.fserver.protocol.InodeDtoOrBuilder getInodeOrBuilder();
}
