// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fs.proto
// Protobuf Java Version: 4.29.3

package snfs.fserver.protocol;

public interface TextMsgDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.TextMsgDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .protocol.ErrStatus status = 1;</code>
   * @return The status.
   */
  snfs.fserver.protocol.ErrStatus getStatus();

  /**
   * <code>optional string text = 2;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>optional string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
